config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  devise_for :admins
  devise_for :users
  resources :discs
  resources :artists
  get 'welcome/index'

  root 'welcome#index'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        flash[:success]= "Se guardo correctamente el artista"
        format.html { redirect_to @artist }
        format.json { render :show, status: :created, location: @artist }
      else
        flash[:alert]= "Erros al guardar el artists"
        format.html { render :new}
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:nombre, :sexo)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="row"> 
		<div class="small-4 column">
		
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre, :class => "validate[required]" %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br>
    <%= f.text_field :sexo, :class => "validate[required]" %>
  </div>
  <div class="actions">
    <%= f.submit 'Aceptar',:class => 'button small' %>
  </div>
  </div>
  </div>
<% end %>

app/views/artists/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation" data-options="is_hover: false">
    <ul class="title-area">
        <li class="name">
            <h1 style="color:#ffffff"> Aplicacion</h1>
        </li>
    </ul>
    
    <section class="top-bar-section" >
        <ul class="left">
            <li class="has-dropdown not-click"><a href="#">MENÚ</a>
                <ul class="dropdown" >
                    <li class="parent-link show-for-small-only"><a class="parent-link js-generated" href="#">Formato</a></li>
                    <li><label>Secciones</label></li>
                    <li><%=link_to 'Artistas', controller: '/artists', action: 'index' %> </li>
                    <li><%=link_to 'Discos', controller: '/discs', action: 'index' %> </li>
                    
                </ul>
            </li>
        </ul>
        
		<ul class="right">
            <%if user_signed_in? %>
            <li><a>Bienvenido(a) <%= current_user.email %></a></li>
            <li><%= link_to "Editar", edit_user_registration_path %></li>
            <li><%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete,  :class => 'navbar-link' %></li>
            <li> <%= link_to 'Nuevo Artista', new_artist_path %></li>
            
            
            
            <% else %>
            <li><%= link_to "Iniciar sesión", new_user_session_path %></li>
            <li><%= link_to "Registrate", new_user_registration_path %></li>
            <% end %>
        
        
        <!--Es para dividir -->
        <li class="divider"></li>
            </ul>
       
           
    </section>
</nav>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Artists</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Sexo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.nombre %></td>
        <td><%= artist.sexo %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @artist.nombre %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @artist.sexo %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>