config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  devise_for :admins
  devise_for :users
  resources :discs
  resources :artists
  get 'welcome/index'

  root 'welcome#index'

end

app/models/disc.rb
class Disc < ActiveRecord::Base
end

app/controllers/discs_controller.rb
class DiscsController < ApplicationController
  before_action :set_disc, only: [:show, :edit, :update, :destroy]

  # GET /discs
  # GET /discs.json
  def index
    @discs = Disc.all
  end

  # GET /discs/1
  # GET /discs/1.json
  def show
  end

  # GET /discs/new
  def new
    @disc = Disc.new
  end

  # GET /discs/1/edit
  def edit
  end

  # POST /discs
  # POST /discs.json
  def create
    @disc = Disc.new(disc_params)

    respond_to do |format|
      if @disc.save
        format.html { redirect_to @disc, notice: 'Disc was successfully created.' }
        format.json { render :show, status: :created, location: @disc }
      else
        format.html { render :new }
        format.json { render json: @disc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discs/1
  # PATCH/PUT /discs/1.json
  def update
    respond_to do |format|
      if @disc.update(disc_params)
        format.html { redirect_to @disc, notice: 'Disc was successfully updated.' }
        format.json { render :show, status: :ok, location: @disc }
      else
        format.html { render :edit }
        format.json { render json: @disc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discs/1
  # DELETE /discs/1.json
  def destroy
    @disc.destroy
    respond_to do |format|
      format.html { redirect_to discs_url, notice: 'Disc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disc
      @disc = Disc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disc_params
      params.require(:disc).permit(:artist_id, :titulo, :fecha, :genero)
    end
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/views/discs/_form.html.erb
<%= form_for(@disc) do |f| %>
  <% if @disc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@disc.errors.count, "error") %> prohibited this disc from being saved:</h2>

      <ul>
      <% @disc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="row"> 
		<div class="small-4 column">
  <div class="field">
    <%= f.label :artist_id %><br>
    <%= f.number_field :artist_id %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo, :class => "validate[required]" %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.text_field :fecha, :class => "validate[required]" %>
  </div>
  <div class="field">
    <%= f.label :genero %><br>
    <%= f.text_field :genero, :class => "validate[required]" %>
  </div>
  <div class="actions">
    <%= f.submit 'Aceptar',:class => 'button small' %>
  </div>
  </div>
  </div>
<% end %>

app/views/discs/edit.html.erb
<h1>Editing Disc</h1>

<%= render 'form' %>

<%= link_to 'Show', @disc %> |
<%= link_to 'Back', discs_path %>

app/views/discs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Discs</h1>

<table>
  <thead>
    <tr>
      <th>Artist</th>
      <th>Titulo</th>
      <th>Fecha</th>
      <th>Genero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discs.each do |disc| %>
      <tr>
        <td><%= disc.artist_id %></td>
        <td><%= disc.titulo %></td>
        <td><%= disc.fecha %></td>
        <td><%= disc.genero %></td>
        <td><%= link_to 'Show', disc %></td>
        <td><%= link_to 'Edit', edit_disc_path(disc) %></td>
        <td><%= link_to 'Destroy', disc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Disc', new_disc_path %>

app/views/discs/new.html.erb
<h1>New Disc</h1>

<%= render 'form' %>

<%= link_to 'Back', discs_path %>

app/views/discs/show.html.erb
<p>
  <strong>Artist:</strong>
  <%= @disc.artist_id %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @disc.titulo %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @disc.fecha %>
</p>

<p>
  <strong>Genero:</strong>
  <%= @disc.genero %>
</p>

<%= link_to 'Edit', edit_disc_path(@disc) %> |
<%= link_to 'Back', discs_path %>